config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :services
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :service
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :services, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[show edit update destroy]

  def index
    @services = Service.all
  end

  def show
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(services_params)
    if @service.save
      redirect_to service_path(@service), notice: 'Service créé avec succès.'
    else
      render 'new', status: unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @service.update(services_params)
      redirect_to service_path(@service), notice: 'Service mis à jour avec succès.'
    else
      render 'edit', status: unprocessable_entity
    end
  end

  def destroy
    @service.destroy
    redirect_to services_path, status: :see_other, notice: 'Service supprimé avec succès.'
  end

  private

  def set_service
    @service = Service.find(params[:id])
  end

  def services_params
    params.require(:service).permit(:name, :photo, :service_type, :address, :price_per_day, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuddyBundleCraft</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="body-container">
<h1>BuddyBundleCraft,<br>des services à prix d’ami !</h1>

<p>Trouvez votre compagnon idéal dans le monde du bricolage pour toutes vos nécessités d'aménagement, de pose, de fixation, de remplacement, de rénovation et de réparation entre particuliers.</p>
  <div class="cards">
  <%= link_to services_path do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://i.ibb.co/dMjQ8R8/bricolage.jpg)">
    Réserver un service
    </div>
  <% end %>

  <%= link_to new_service_path do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://i.ibb.co/7b9PBhz/bricolage2.jpg)">
    Proposer un service
    </div>
  <% end %>
  </div>
</div>

app/views/services/index.html.erb
<div class="body-container">
<h1>Buddy Bundle Craft,<br>des services à prix d’ami !</h1>
  <div class="cards">
      <% @services.each do |service| %>
        <%= link_to service_path(service) do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://i.ibb.co/dMjQ8R8/bricolage.jpg)">
          <div class="d-flex flex-column">
            <div><%= service.name %></div>
            <div><%= service.service_type %></div>
            <div><%= service.address %></div>
            <div><%= service.price_per_hour.to_i %> €</div>
          </div>
    </div>
        <% end %>
      <% end %>
  </div>
</div>

app/views/services/show.html.erb
<div class="body-container">
 <% if @service.photo.attached? %>
      <%= cl_image_tag(@service.photo.key, alt: (@service.name + "-picture"), class: "builder-photo") %>
    <% else %>
      <%= cl_image_tag('bpcnwcjphzkf25eryqj9', class: "builder-photo") %>
    <% end %>
  <div><%= @service.name %></div>
  <div><%= @service.service_type %></div>
  <div><%= @service.address %></div>
  <div><%= @service.price_per_hour.to_i %> €</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "logo-inline.png", class: "nav-logo" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>